FROM loadimpact/k6:latest AS k6official
FROM jenkins/agent:latest-alpine3.18-jdk17

COPY --from=k6official /usr/bin/k6 /usr/bin/k6

USER root

RUN apk update
RUN apk add python3 py3-pip make docker docker-cli-compose openrc npm nodejs procps

# Setup Jenkins permissions for docker.sock
RUN apk --no-cache add shadow
RUN addgroup jenkins docker
RUN groupmod --gid 1001 docker
RUN usermod -aG docker jenkins
RUN apk del shadow

USER jenkins